/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EmpreendimentosRouteImport } from './routes/empreendimentos'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as QueroInvestirRouteImport } from './routes/quero-investir'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as ConviteCodigoRouteImport } from './routes/convite.$codigo'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminComprasRouteImport } from './routes/_authenticated/admin/compras'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin/crm'
import { Route as AuthenticatedAdminEmpreendimentosRouteImport } from './routes/_authenticated/admin/empreendimentos'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminOrcamentoRouteImport } from './routes/_authenticated/admin/orcamento'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin/relatorios'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalComunicadosRouteImport } from './routes/_authenticated/portal/comunicados'
import { Route as AuthenticatedPortalDocumentosRouteImport } from './routes/_authenticated/portal/documentos'
import { Route as AuthenticatedPortalEmpreendimentosRouteImport } from './routes/_authenticated/portal/empreendimentos'
import { Route as AuthenticatedPortalIndiqueRouteImport } from './routes/_authenticated/portal/indique'
import { Route as AuthenticatedPortalInvestimentosRouteImport } from './routes/_authenticated/portal/investimentos'
import { Route as AuthenticatedPortalPerfilRouteImport } from './routes/_authenticated/portal/perfil'
import { Route as AuthenticatedAdminEmpreendimentosIndexRouteImport } from './routes/_authenticated/admin/empreendimentos.index'
import { Route as AuthenticatedAdminEmpreendimentosIdRouteImport } from './routes/_authenticated/admin/empreendimentos/$id'
import { Route as AuthenticatedPortalEmpreendimentosIndexRouteImport } from './routes/_authenticated/portal/empreendimentos.index'
import { Route as AuthenticatedPortalEmpreendimentosIdRouteImport } from './routes/_authenticated/portal/empreendimentos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosRoute = EmpreendimentosRouteImport.update({
  id: '/empreendimentos',
  path: '/empreendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const QueroInvestirRoute = QueroInvestirRouteImport.update({
  id: '/quero-investir',
  path: '/quero-investir',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteCodigoRoute = ConviteCodigoRouteImport.update({
  id: '/convite/$codigo',
  path: '/convite/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminComprasRoute =
  AuthenticatedAdminComprasRouteImport.update({
    id: '/compras',
    path: '/compras',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmpreendimentosRoute =
  AuthenticatedAdminEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrcamentoRoute =
  AuthenticatedAdminOrcamentoRouteImport.update({
    id: '/orcamento',
    path: '/orcamento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalComunicadosRoute =
  AuthenticatedPortalComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentosRoute =
  AuthenticatedPortalDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalEmpreendimentosRoute =
  AuthenticatedPortalEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalIndiqueRoute =
  AuthenticatedPortalIndiqueRouteImport.update({
    id: '/indique',
    path: '/indique',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalInvestimentosRoute =
  AuthenticatedPortalInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPerfilRoute =
  AuthenticatedPortalPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminEmpreendimentosIndexRoute =
  AuthenticatedAdminEmpreendimentosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEmpreendimentosRoute,
  } as any)
const AuthenticatedAdminEmpreendimentosIdRoute =
  AuthenticatedAdminEmpreendimentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEmpreendimentosRoute,
  } as any)
const AuthenticatedPortalEmpreendimentosIndexRoute =
  AuthenticatedPortalEmpreendimentosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalEmpreendimentosRoute,
  } as any)
const AuthenticatedPortalEmpreendimentosIdRoute =
  AuthenticatedPortalEmpreendimentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalEmpreendimentosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRouteWithChildren
  '/metodologia': typeof MetodologiaRoute
  '/quero-investir': typeof QueroInvestirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/convite/$codigo': typeof ConviteCodigoRoute
  '/login/admin': typeof LoginAdminRoute
  '/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/empreendimentos': typeof AuthenticatedAdminEmpreendimentosRouteWithChildren
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/orcamento': typeof AuthenticatedAdminOrcamentoRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/portal/comunicados': typeof AuthenticatedPortalComunicadosRoute
  '/portal/documentos': typeof AuthenticatedPortalDocumentosRoute
  '/portal/empreendimentos': typeof AuthenticatedPortalEmpreendimentosRouteWithChildren
  '/portal/indique': typeof AuthenticatedPortalIndiqueRoute
  '/portal/investimentos': typeof AuthenticatedPortalInvestimentosRoute
  '/portal/perfil': typeof AuthenticatedPortalPerfilRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/empreendimentos/$id': typeof AuthenticatedAdminEmpreendimentosIdRoute
  '/portal/empreendimentos/$id': typeof AuthenticatedPortalEmpreendimentosIdRoute
  '/admin/empreendimentos/': typeof AuthenticatedAdminEmpreendimentosIndexRoute
  '/portal/empreendimentos/': typeof AuthenticatedPortalEmpreendimentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRouteWithChildren
  '/metodologia': typeof MetodologiaRoute
  '/quero-investir': typeof QueroInvestirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/convite/$codigo': typeof ConviteCodigoRoute
  '/login/admin': typeof LoginAdminRoute
  '/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/orcamento': typeof AuthenticatedAdminOrcamentoRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/portal/comunicados': typeof AuthenticatedPortalComunicadosRoute
  '/portal/documentos': typeof AuthenticatedPortalDocumentosRoute
  '/portal/indique': typeof AuthenticatedPortalIndiqueRoute
  '/portal/investimentos': typeof AuthenticatedPortalInvestimentosRoute
  '/portal/perfil': typeof AuthenticatedPortalPerfilRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/empreendimentos/$id': typeof AuthenticatedAdminEmpreendimentosIdRoute
  '/portal/empreendimentos/$id': typeof AuthenticatedPortalEmpreendimentosIdRoute
  '/admin/empreendimentos': typeof AuthenticatedAdminEmpreendimentosIndexRoute
  '/portal/empreendimentos': typeof AuthenticatedPortalEmpreendimentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empreendimentos': typeof EmpreendimentosRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRouteWithChildren
  '/metodologia': typeof MetodologiaRoute
  '/quero-investir': typeof QueroInvestirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/convite/$codigo': typeof ConviteCodigoRoute
  '/login/admin': typeof LoginAdminRoute
  '/_authenticated/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/empreendimentos': typeof AuthenticatedAdminEmpreendimentosRouteWithChildren
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/orcamento': typeof AuthenticatedAdminOrcamentoRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/portal/comunicados': typeof AuthenticatedPortalComunicadosRoute
  '/_authenticated/portal/documentos': typeof AuthenticatedPortalDocumentosRoute
  '/_authenticated/portal/empreendimentos': typeof AuthenticatedPortalEmpreendimentosRouteWithChildren
  '/_authenticated/portal/indique': typeof AuthenticatedPortalIndiqueRoute
  '/_authenticated/portal/investimentos': typeof AuthenticatedPortalInvestimentosRoute
  '/_authenticated/portal/perfil': typeof AuthenticatedPortalPerfilRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/empreendimentos/$id': typeof AuthenticatedAdminEmpreendimentosIdRoute
  '/_authenticated/portal/empreendimentos/$id': typeof AuthenticatedPortalEmpreendimentosIdRoute
  '/_authenticated/admin/empreendimentos/': typeof AuthenticatedAdminEmpreendimentosIndexRoute
  '/_authenticated/portal/empreendimentos/': typeof AuthenticatedPortalEmpreendimentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/empreendimentos'
    | '/insights'
    | '/login'
    | '/metodologia'
    | '/quero-investir'
    | '/reset-password'
    | '/sobre'
    | '/admin'
    | '/portal'
    | '/convite/$codigo'
    | '/login/admin'
    | '/admin/compras'
    | '/admin/crm'
    | '/admin/empreendimentos'
    | '/admin/financeiro'
    | '/admin/orcamento'
    | '/admin/relatorios'
    | '/portal/comunicados'
    | '/portal/documentos'
    | '/portal/empreendimentos'
    | '/portal/indique'
    | '/portal/investimentos'
    | '/portal/perfil'
    | '/admin/'
    | '/portal/'
    | '/admin/empreendimentos/$id'
    | '/portal/empreendimentos/$id'
    | '/admin/empreendimentos/'
    | '/portal/empreendimentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/empreendimentos'
    | '/insights'
    | '/login'
    | '/metodologia'
    | '/quero-investir'
    | '/reset-password'
    | '/sobre'
    | '/convite/$codigo'
    | '/login/admin'
    | '/admin/compras'
    | '/admin/crm'
    | '/admin/financeiro'
    | '/admin/orcamento'
    | '/admin/relatorios'
    | '/portal/comunicados'
    | '/portal/documentos'
    | '/portal/indique'
    | '/portal/investimentos'
    | '/portal/perfil'
    | '/admin'
    | '/portal'
    | '/admin/empreendimentos/$id'
    | '/portal/empreendimentos/$id'
    | '/admin/empreendimentos'
    | '/portal/empreendimentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/como-funciona'
    | '/contato'
    | '/empreendimentos'
    | '/insights'
    | '/login'
    | '/metodologia'
    | '/quero-investir'
    | '/reset-password'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/convite/$codigo'
    | '/login/admin'
    | '/_authenticated/admin/compras'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/empreendimentos'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/orcamento'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/portal/comunicados'
    | '/_authenticated/portal/documentos'
    | '/_authenticated/portal/empreendimentos'
    | '/_authenticated/portal/indique'
    | '/_authenticated/portal/investimentos'
    | '/_authenticated/portal/perfil'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/empreendimentos/$id'
    | '/_authenticated/portal/empreendimentos/$id'
    | '/_authenticated/admin/empreendimentos/'
    | '/_authenticated/portal/empreendimentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  EmpreendimentosRoute: typeof EmpreendimentosRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRouteWithChildren
  MetodologiaRoute: typeof MetodologiaRoute
  QueroInvestirRoute: typeof QueroInvestirRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  ConviteCodigoRoute: typeof ConviteCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos': {
      id: '/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof EmpreendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quero-investir': {
      id: '/quero-investir'
      path: '/quero-investir'
      fullPath: '/quero-investir'
      preLoaderRoute: typeof QueroInvestirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$codigo': {
      id: '/convite/$codigo'
      path: '/convite/$codigo'
      fullPath: '/convite/$codigo'
      preLoaderRoute: typeof ConviteCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/compras': {
      id: '/_authenticated/admin/compras'
      path: '/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AuthenticatedAdminComprasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empreendimentos': {
      id: '/_authenticated/admin/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/admin/empreendimentos'
      preLoaderRoute: typeof AuthenticatedAdminEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orcamento': {
      id: '/_authenticated/admin/orcamento'
      path: '/orcamento'
      fullPath: '/admin/orcamento'
      preLoaderRoute: typeof AuthenticatedAdminOrcamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/comunicados': {
      id: '/_authenticated/portal/comunicados'
      path: '/comunicados'
      fullPath: '/portal/comunicados'
      preLoaderRoute: typeof AuthenticatedPortalComunicadosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documentos': {
      id: '/_authenticated/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof AuthenticatedPortalDocumentosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/empreendimentos': {
      id: '/_authenticated/portal/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/portal/empreendimentos'
      preLoaderRoute: typeof AuthenticatedPortalEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/indique': {
      id: '/_authenticated/portal/indique'
      path: '/indique'
      fullPath: '/portal/indique'
      preLoaderRoute: typeof AuthenticatedPortalIndiqueRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/investimentos': {
      id: '/_authenticated/portal/investimentos'
      path: '/investimentos'
      fullPath: '/portal/investimentos'
      preLoaderRoute: typeof AuthenticatedPortalInvestimentosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/perfil': {
      id: '/_authenticated/portal/perfil'
      path: '/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof AuthenticatedPortalPerfilRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/empreendimentos/': {
      id: '/_authenticated/admin/empreendimentos/'
      path: '/'
      fullPath: '/admin/empreendimentos/'
      preLoaderRoute: typeof AuthenticatedAdminEmpreendimentosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEmpreendimentosRoute
    }
    '/_authenticated/admin/empreendimentos/$id': {
      id: '/_authenticated/admin/empreendimentos/$id'
      path: '/$id'
      fullPath: '/admin/empreendimentos/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmpreendimentosIdRouteImport
      parentRoute: typeof AuthenticatedAdminEmpreendimentosRoute
    }
    '/_authenticated/portal/empreendimentos/': {
      id: '/_authenticated/portal/empreendimentos/'
      path: '/'
      fullPath: '/portal/empreendimentos/'
      preLoaderRoute: typeof AuthenticatedPortalEmpreendimentosIndexRouteImport
      parentRoute: typeof AuthenticatedPortalEmpreendimentosRoute
    }
    '/_authenticated/portal/empreendimentos/$id': {
      id: '/_authenticated/portal/empreendimentos/$id'
      path: '/$id'
      fullPath: '/portal/empreendimentos/$id'
      preLoaderRoute: typeof AuthenticatedPortalEmpreendimentosIdRouteImport
      parentRoute: typeof AuthenticatedPortalEmpreendimentosRoute
    }
  }
}

interface AuthenticatedAdminEmpreendimentosRouteChildren {
  AuthenticatedAdminEmpreendimentosIdRoute: typeof AuthenticatedAdminEmpreendimentosIdRoute
  AuthenticatedAdminEmpreendimentosIndexRoute: typeof AuthenticatedAdminEmpreendimentosIndexRoute
}

const AuthenticatedAdminEmpreendimentosRouteChildren: AuthenticatedAdminEmpreendimentosRouteChildren =
  {
    AuthenticatedAdminEmpreendimentosIdRoute:
      AuthenticatedAdminEmpreendimentosIdRoute,
    AuthenticatedAdminEmpreendimentosIndexRoute:
      AuthenticatedAdminEmpreendimentosIndexRoute,
  }

const AuthenticatedAdminEmpreendimentosRouteWithChildren =
  AuthenticatedAdminEmpreendimentosRoute._addFileChildren(
    AuthenticatedAdminEmpreendimentosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminComprasRoute: typeof AuthenticatedAdminComprasRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminEmpreendimentosRoute: typeof AuthenticatedAdminEmpreendimentosRouteWithChildren
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminOrcamentoRoute: typeof AuthenticatedAdminOrcamentoRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminComprasRoute: AuthenticatedAdminComprasRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminEmpreendimentosRoute:
    AuthenticatedAdminEmpreendimentosRouteWithChildren,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminOrcamentoRoute: AuthenticatedAdminOrcamentoRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalEmpreendimentosRouteChildren {
  AuthenticatedPortalEmpreendimentosIdRoute: typeof AuthenticatedPortalEmpreendimentosIdRoute
  AuthenticatedPortalEmpreendimentosIndexRoute: typeof AuthenticatedPortalEmpreendimentosIndexRoute
}

const AuthenticatedPortalEmpreendimentosRouteChildren: AuthenticatedPortalEmpreendimentosRouteChildren =
  {
    AuthenticatedPortalEmpreendimentosIdRoute:
      AuthenticatedPortalEmpreendimentosIdRoute,
    AuthenticatedPortalEmpreendimentosIndexRoute:
      AuthenticatedPortalEmpreendimentosIndexRoute,
  }

const AuthenticatedPortalEmpreendimentosRouteWithChildren =
  AuthenticatedPortalEmpreendimentosRoute._addFileChildren(
    AuthenticatedPortalEmpreendimentosRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalComunicadosRoute: typeof AuthenticatedPortalComunicadosRoute
  AuthenticatedPortalDocumentosRoute: typeof AuthenticatedPortalDocumentosRoute
  AuthenticatedPortalEmpreendimentosRoute: typeof AuthenticatedPortalEmpreendimentosRouteWithChildren
  AuthenticatedPortalIndiqueRoute: typeof AuthenticatedPortalIndiqueRoute
  AuthenticatedPortalInvestimentosRoute: typeof AuthenticatedPortalInvestimentosRoute
  AuthenticatedPortalPerfilRoute: typeof AuthenticatedPortalPerfilRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalComunicadosRoute: AuthenticatedPortalComunicadosRoute,
  AuthenticatedPortalDocumentosRoute: AuthenticatedPortalDocumentosRoute,
  AuthenticatedPortalEmpreendimentosRoute:
    AuthenticatedPortalEmpreendimentosRouteWithChildren,
  AuthenticatedPortalIndiqueRoute: AuthenticatedPortalIndiqueRoute,
  AuthenticatedPortalInvestimentosRoute: AuthenticatedPortalInvestimentosRoute,
  AuthenticatedPortalPerfilRoute: AuthenticatedPortalPerfilRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  EmpreendimentosRoute: EmpreendimentosRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRouteWithChildren,
  MetodologiaRoute: MetodologiaRoute,
  QueroInvestirRoute: QueroInvestirRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  ConviteCodigoRoute: ConviteCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
