import { createFileRoute, Link } from "@tanstack/react-router";
import { AdminHeading, useAdmin } from "@/components/admin/AdminLayout";
import { projectSummary } from "@/lib/data/admin-calculations";
import { brl, dateBR } from "@/lib/format";
export const Route = createFileRoute("/_authenticated/admin/empreendimentos/$id")({ head: () => ({ meta: [
  { title: "Detalhe do empreendimento — Administração MD70" }, { name: "description", content: "Caixa, orçamento, financeiro e compras do empreendimento na área interna MD70." },
  { property: "og:title", content: "Detalhe administrativo MD70" }, { property: "og:description", content: "Informações internas de empreendimento MD70." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: Detail });
function Detail(){const {id}=Route.useParams();const{data}=useAdmin();const s=projectSummary(data,id);if(!s.project)return <p className="text-sm">Empreendimento não encontrado. <Link to="/admin/empreendimentos" className="text-primary underline">Voltar</Link></p>;const budgets=data.budgets.filter(b=>b.projectId===id);const movements=data.movements.filter(m=>m.projectId===id);const purchases=data.purchases.filter(p=>p.projectId===id);return <><Link to="/admin/empreendimentos" className="text-xs text-muted-foreground underline underline-offset-4">← Empreendimentos</Link><div className="mt-5"><AdminHeading title={s.project.name}>{s.project.status} · obra {s.project.progress}%</AdminHeading></div><section className="grid gap-px border bg-border sm:grid-cols-2 lg:grid-cols-4">{[["Capital aportado",s.capital],["Caixa disponível",s.cash],["Orçamento",s.budget],["Realizado",s.spent],["Comprometido",s.committed],["Forecast",s.forecast],["Saldo de orçamento",s.balance]].map(([l,v])=><div key={l} className="bg-card p-5"><p className="text-xs text-muted-foreground">{l}</p><p className="num mt-2 font-display text-2xl text-primary">{brl(Number(v))}</p></div>)}</section><section className="mt-10"><h2 className="font-display text-3xl text-primary">Orçamento</h2><div className="mt-4 overflow-x-auto border"><table className="w-full min-w-[650px] text-sm"><thead><tr className="bg-muted text-left text-xs text-muted-foreground">{["Categoria / item","Orçado","Realizado","Comprometido","Forecast","Saldo"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{budgets.map(b=>{const forecast=b.realized+b.committed+b.remaining;return <tr key={b.id} className="border-t"><td className="p-3 font-medium">{b.category} / {b.item}</td>{[b.planned,b.realized,b.committed,forecast,b.planned-forecast].map((v,i)=><td key={i} className="num p-3">{brl(v)}</td>)}</tr>})}</tbody></table></div></section><section className="mt-10"><h2 className="font-display text-3xl text-primary">Financeiro</h2><div className="mt-4 divide-y border-y">{movements.map(m=><div key={m.id} className="grid grid-cols-[minmax(0,1fr)_auto] gap-3 py-4 text-sm"><div className="min-w-0"><p className="font-medium">{m.description}</p><p className="text-xs text-muted-foreground">{dateBR(m.date)} · {m.category} · {m.status}</p></div><span className="num shrink-0">{m.direction==="Saída"?"−":"+"}{brl(m.value)}</span></div>)}</div></section><section className="mt-10"><h2 className="font-display text-3xl text-primary">Compras</h2><div className="mt-4 divide-y border-y">{purchases.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 py-4 text-sm"><span>{p.description}</span><span className="text-muted-foreground">{p.status} · {brl(p.estimate)}</span></div>)}</div></section></>}