"""backend package."""

# Imports commented due to invalid module names with hyphens (for testing purposes)
# Restore these after fixing module names from server-backend to server_backend, etc.

# from . import Data
# from . import App
# from . import scripts

# from .Main import main
# from .server-backend import Config, UploadCredentials, SelectiveStatusFilter, SilentRequestHandler, UploadLogger, DatabaseManager, SchemaManager, SecureDatabase, UnifiedDBManagingService, DataEncryption, SimpleCrypto, LightweightCrypto, LightweightBackupService, FastFileValidator, UploadCategoryValidator, LocalUploadManager, ImgWebP, UploadWorkflowOrchestrator, PostUploadWorkflowManager, ImgRGB, VisualAnalysis, PropertyAnalysisEngine, CampaignBriefingGenerator, ImgUtils, ImgAngComb, ImgLayoutComb, ImgMix, CampaignScheduler, VideoAV1, MetaAdsManager, CampaignPerformanceMonitor, AppServer, async_route, sanitize_for_logging, log_detailed_request, log_detailed_response, log_debug_mode_status, log_request_start, selective_logging, add_error_source_header, get_db, close_db, get_client_ip, validate_input, log_api_call, create_data_encryption, encrypt_sensitive_fields, decrypt_sensitive_fields, detect_volume_mounts, initialize_database_system_with_volumes, calculate_file_hash, check_duplicate_hash, analyze_folder_structure, analyze_media_structure_internal, detect_columns_for_mapping, upload_avatar, upload_logo_primary, upload_logo_secondary, serve_upload, uploads_health, get_campaign_performance, signal_handler, handle_command
# from .server-core import Config, SelectiveStatusFilter, DatabaseManager, SecureDatabase, ClientService, DatabaseService, DataEncryption, SimpleCrypto, ValidationError, OAuthTokenManager, InvitationService, GoogleEmailService, RecoverySchemas, PasswordRecoveryUtils, NotificationService, PasswordRecoveryDB, AIService, CompanyInvitationService, UserManagementService, CreditsService, sanitize_for_logging, log_detailed_request, log_detailed_response, log_debug_mode_status, log_request_start, selective_logging, add_error_source_header, proxy_to_backend_service, encrypt_sensitive_fields, decrypt_sensitive_fields, create_data_encryption, get_db, close_db, get_client_ip, validate_input, log_api_call, verify_internal_token, create_validation_middleware, validate_tax_id, check_user_limit, setup_google_oauth_routes, authenticate_token, require_role, generate_access_token, generate_refresh_token, hash_refresh_token, setup_auth_routes, create_recovery_routes, setup_oauth_management_routes, setup_profile_routes, setup_chat_routes, calculate_diversification_score, calculate_risk_balance_score, calculate_growth_potential_score, setup_campaigns_routes, setup_portfolio_routes, setup_insights_routes, setup_approvals_routes, setup_user_management_routes, setup_credits_routes, setup_billing_routes, setup_data_mapping_routes, setup_integration_token_routes, log_streaming_request, proxy_backend_service_data_mapping, proxy_to_backend_service_streaming, setup_universal_upload_proxy, signal_handler

__all__ = [
    # Main
    "main",
    # server-backend
    "Config",
    "UploadCredentials",
    "SelectiveStatusFilter",
    "SilentRequestHandler",
    "UploadLogger",
    "DatabaseManager",
    "SchemaManager",
    "SecureDatabase",
    "UnifiedDBManagingService",
    "DataEncryption",
    "SimpleCrypto",
    "LightweightCrypto",
    "LightweightBackupService",
    "FastFileValidator",
    "UploadCategoryValidator",
    "LocalUploadManager",
    "ImgWebP",
    "UploadWorkflowOrchestrator",
    "PostUploadWorkflowManager",
    "ImgRGB",
    "VisualAnalysis",
    "PropertyAnalysisEngine",
    "CampaignBriefingGenerator",
    "ImgUtils",
    "ImgAngComb",
    "ImgLayoutComb",
    "ImgMix",
    "CampaignScheduler",
    "VideoAV1",
    "MetaAdsManager",
    "CampaignPerformanceMonitor",
    "AppServer",
    "async_route",
    "sanitize_for_logging",
    "log_detailed_request",
    "log_detailed_response",
    "log_debug_mode_status",
    "log_request_start",
    "selective_logging",
    "add_error_source_header",
    "get_db",
    "close_db",
    "get_client_ip",
    "validate_input",
    "log_api_call",
    "create_data_encryption",
    "encrypt_sensitive_fields",
    "decrypt_sensitive_fields",
    "detect_volume_mounts",
    "initialize_database_system_with_volumes",
    "calculate_file_hash",
    "check_duplicate_hash",
    "analyze_folder_structure",
    "analyze_media_structure_internal",
    "detect_columns_for_mapping",
    "upload_avatar",
    "upload_logo_primary",
    "upload_logo_secondary",
    "serve_upload",
    "uploads_health",
    "get_campaign_performance",
    "signal_handler",
    "handle_command",
    # server-core
    "Config",
    "SelectiveStatusFilter",
    "DatabaseManager",
    "SecureDatabase",
    "ClientService",
    "DatabaseService",
    "DataEncryption",
    "SimpleCrypto",
    "ValidationError",
    "OAuthTokenManager",
    "InvitationService",
    "GoogleEmailService",
    "RecoverySchemas",
    "PasswordRecoveryUtils",
    "NotificationService",
    "PasswordRecoveryDB",
    "AIService",
    "CompanyInvitationService",
    "UserManagementService",
    "CreditsService",
    "sanitize_for_logging",
    "log_detailed_request",
    "log_detailed_response",
    "log_debug_mode_status",
    "log_request_start",
    "selective_logging",
    "add_error_source_header",
    "proxy_to_backend_service",
    "encrypt_sensitive_fields",
    "decrypt_sensitive_fields",
    "create_data_encryption",
    "get_db",
    "close_db",
    "get_client_ip",
    "validate_input",
    "log_api_call",
    "verify_internal_token",
    "create_validation_middleware",
    "validate_tax_id",
    "check_user_limit",
    "setup_google_oauth_routes",
    "authenticate_token",
    "require_role",
    "generate_access_token",
    "generate_refresh_token",
    "hash_refresh_token",
    "setup_auth_routes",
    "create_recovery_routes",
    "setup_oauth_management_routes",
    "setup_profile_routes",
    "setup_chat_routes",
    "calculate_diversification_score",
    "calculate_risk_balance_score",
    "calculate_growth_potential_score",
    "setup_campaigns_routes",
    "setup_portfolio_routes",
    "setup_insights_routes",
    "setup_approvals_routes",
    "setup_user_management_routes",
    "setup_credits_routes",
    "setup_billing_routes",
    "setup_data_mapping_routes",
    "setup_integration_token_routes",
    "log_streaming_request",
    "proxy_backend_service_data_mapping",
    "proxy_to_backend_service_streaming",
    "setup_universal_upload_proxy",
    "signal_handler",
]
