import { createFileRoute, notFound } from "@tanstack/react-router";
import { useState } from "react";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { BudgetChart } from "@/components/portal/BudgetChart";
import { Button } from "@/components/ui/button";
import { getDevelopment } from "@/lib/data/developments";
import { getInvestmentByDevelopment } from "@/lib/data/portal";
import { brl, dateBR, pct } from "@/lib/format";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/portal/empreendimentos/$id")({
  beforeLoad: ({ params }) => { if (!getDevelopment(params.id)) throw notFound(); },
  head: ({ params }) => { const d=getDevelopment(params.id); const title=d?`${d.name} — Portal MD70`:"Empreendimento — Portal MD70"; return {meta:[{title},{name:"description",content:"Acompanhamento privado do empreendimento."},{property:"og:title",content:title},{property:"og:description",content:"Obra, orçamento e resultados do projeto."}]}; },
  component: Project,
  notFoundComponent: () => <div className="py-20 text-center"><h1 className="font-display text-4xl text-primary">Empreendimento não encontrado.</h1></div>,
});

type Tab="obra"|"orcamento"|"resultado";
function Project(){const{id}=Route.useParams();const d=getDevelopment(id);if(!d)return null;const inv=getInvestmentByDevelopment(id);const[slide,setSlide]=useState(0);const[tab,setTab]=useState<Tab>("obra");const[lightbox,setLightbox]=useState<string|null>(null);const gallery=d.gallery;return <><section className="grid gap-0 border bg-card lg:grid-cols-[1.35fr_1fr]"><div className="relative min-h-[22rem] overflow-hidden bg-muted"><img src={gallery[slide]?.src??d.image} alt={gallery[slide]?.caption??d.name} className="photo absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-foreground/70 to-transparent p-5 text-primary-foreground"><p className="text-sm">{gallery[slide]?.caption}</p><span className="num text-xs">{slide+1} / {gallery.length}</span></div>{gallery.length>1&&<><Button variant="secondary" size="icon" className="absolute left-3 top-1/2 -translate-y-1/2" onClick={()=>setSlide((slide-1+gallery.length)%gallery.length)} aria-label="Imagem anterior"><ChevronLeft/></Button><Button variant="secondary" size="icon" className="absolute right-3 top-1/2 -translate-y-1/2" onClick={()=>setSlide((slide+1)%gallery.length)} aria-label="Próxima imagem"><ChevronRight/></Button></>}</div><div className="p-7 md:p-10"><p className="eyebrow">{d.city} · {d.category}</p><h1 className="mt-3 font-display text-5xl text-primary">{d.name}</h1><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{d.summary}</p><div className="mt-8 grid grid-cols-2 gap-5 border-t pt-6"><Metric label="Status" value={d.status}/><Metric label="Investido" value={brl(inv?.invested??0)}/><Metric label="Participação" value={pct(inv?.share??0)}/><Metric label="Previsão" value={dateBR(d.forecast)}/></div><div className="mt-7"><div className="flex justify-between text-xs"><span>Realizado {d.progress}%</span><span>Previsto {d.plannedProgress}%</span></div><div className="mt-2 h-2 bg-muted"><div className="h-full bg-primary" style={{width:`${d.progress}%`}}/></div><p className="mt-3 text-xs text-muted-foreground">Etapa atual: {d.currentStage} · Próxima: {d.nextStage}</p></div></div></section>
<section className="mt-8 border bg-card p-7 md:p-9"><p className="eyebrow">Tese do projeto</p><h2 className="mt-3 font-display text-3xl text-primary">Business plan</h2><div className="mt-7 grid gap-8 md:grid-cols-3"><Text title="Oportunidade" text={d.plan.opportunity}/><Text title="Mercado" text={d.plan.market}/><Text title="Estratégia" text={d.plan.strategy}/></div><div className="mt-8 grid gap-px bg-border border sm:grid-cols-3 lg:grid-cols-5">{d.plan.assumptions.map(a=><div key={a.label} className="bg-card p-5"><p className="text-xs text-muted-foreground">{a.label}</p><p className="num mt-2 font-semibold">{a.value}</p></div>)}</div><div className="mt-8 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Cenário</th><th className="p-3 text-right">Conservador</th><th className="bg-primary/5 p-3 text-right text-primary">Base</th><th className="p-3 text-right">Otimista</th></tr></thead><tbody>{d.scenarios.map(s=><tr key={s.row} className="border-b"><td className="p-3 font-medium">{s.row}</td><td className="num p-3 text-right">{s.conservative}</td><td className="num bg-primary/5 p-3 text-right font-semibold">{s.base}</td><td className="num p-3 text-right">{s.optimistic}</td></tr>)}</tbody></table></div></section>
<section className="mt-8"><div className="flex overflow-x-auto border-b">{([['obra','Obra'],['orcamento','Orçamento'],['resultado','Resultado']] as const).map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={cn("min-w-32 border-b-2 px-6 py-4 text-sm font-semibold",tab===v?"border-primary text-primary":"border-transparent text-muted-foreground")}>{l}</button>)}</div><div className="bg-card border-x border-b p-6 md:p-9">{tab==="obra"&&<Obra d={d} onImage={setLightbox}/>} {tab==="orcamento"&&<Orcamento d={d}/>} {tab==="resultado"&&<Resultado d={d}/>}</div></section>
<section className="mt-8 border bg-card p-7 md:p-9"><p className="eyebrow">Setembro de 2026</p><h2 className="mt-3 font-display text-3xl text-primary">O que mudou neste mês?</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{d.monthChanges.map((c,i)=><div key={i} className={cn("border-l-2 p-4 text-sm",c.tone==='positive'?"border-positive bg-positive/5":c.tone==='attention'?"border-warning bg-warning/5":"border-border bg-muted/40")}>{c.text}</div>)}</div><p className="mt-6 text-sm text-muted-foreground"><strong className="text-foreground">Impacto estimado:</strong> {d.monthImpact}</p></section>
{lightbox&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/90 p-4" onClick={()=>setLightbox(null)}><Button variant="secondary" size="icon" className="absolute right-5 top-5" aria-label="Fechar"><X/></Button><img src={lightbox} alt="Registro ampliado" className="max-h-[90vh] max-w-full object-contain"/></div>}</>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="num mt-1 font-semibold">{value}</p></div>};function Text({title,text}:{title:string;text:string}){return <div><h3 className="font-semibold text-primary">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>}
function Obra({d,onImage}:{d:NonNullable<ReturnType<typeof getDevelopment>>;onImage:(s:string)=>void}){return <div><h3 className="font-display text-3xl text-primary">Cronograma físico</h3><div className="mt-6 overflow-x-auto"><div className="min-w-[650px]"><div className="grid grid-cols-[11rem_repeat(6,1fr)] border-b text-xs text-muted-foreground"><span className="p-3">Etapa</span>{d.ganttMonths.map(m=><span className="p-3 text-center" key={m}>{m}</span>)}</div>{d.milestones.map(m=><div className="grid grid-cols-[11rem_repeat(6,1fr)] border-b py-2 text-xs" key={m.stage}><span className="p-2">{m.stage}<small className="block text-muted-foreground">{m.done}%</small></span>{d.ganttMonths.map((_,i)=><span key={i} className="p-2"><i className={cn("block h-5",i>=m.start&&i<=m.end?m.done===100?"bg-positive":"bg-primary/70":"bg-muted")}/></span>)}</div>)}</div></div><h3 className="mt-10 font-display text-3xl text-primary">Diário da obra</h3><div className="mt-6 space-y-7 border-l">{d.diary.map(e=><article key={e.date} className="relative pl-7"><i className="absolute -left-1 top-1.5 h-2 w-2 rounded-full bg-primary"/><p className="text-xs text-muted-foreground">{dateBR(e.date)}</p><h4 className="mt-1 font-semibold">{e.title}</h4><p className="mt-2 text-sm text-muted-foreground">{e.description}</p><div className="mt-3 flex gap-2 overflow-x-auto">{e.images.map((img,i)=><button key={i} onClick={()=>onImage(img)}><img src={img} alt="" className="photo h-24 w-32 object-cover"/></button>)}</div></article>)}</div></div>}
function Orcamento({d}:{d:NonNullable<ReturnType<typeof getDevelopment>>}){return <div><h3 className="font-display text-3xl text-primary">Previsto x realizado</h3><div className="mt-6"><BudgetChart data={d.budgetSeries}/></div><div className="mt-8 overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Categoria</th><th className="p-3 text-right">Previsto</th><th className="p-3 text-right">Realizado</th><th className="p-3 text-right">Variação</th></tr></thead><tbody>{d.budgetItems.map(b=><tr key={b.category} className="border-b"><td className="p-3">{b.category}</td><td className="num p-3 text-right">{brl(b.planned)}</td><td className="num p-3 text-right">{brl(b.actual)}</td><td className={cn("num p-3 text-right",b.actual<=b.planned?"text-positive":"text-destructive")}>{pct(((b.actual-b.planned)/b.planned)*100)}</td></tr>)}</tbody></table></div></div>}
function Resultado({d}:{d:NonNullable<ReturnType<typeof getDevelopment>>}){return <div><h3 className="font-display text-3xl text-primary">Plano x posição atual</h3><div className="mt-6 grid gap-px bg-border border sm:grid-cols-2 lg:grid-cols-3">{d.result.map(r=><div key={r.label} className="bg-card p-6"><p className="text-xs text-muted-foreground">{r.label}</p><div className="mt-4 flex items-end justify-between gap-3"><div><small className="text-muted-foreground">Plano</small><p className="num mt-1">{r.planned}</p></div><div className="text-right"><small className="text-muted-foreground">{r.kind}</small><p className="num mt-1 text-xl font-semibold text-primary">{r.updated}</p></div></div></div>)}</div><p className="mt-6 text-xs text-muted-foreground">Estimativas podem mudar ao longo do projeto e não representam garantia de rentabilidade.</p></div>}
