import { createFileRoute, Link } from "@tanstack/react-router";
import { PortalHeading } from "@/components/portal/PortalLayout";
import { getInvestorDevelopments, getInvestmentByDevelopment } from "@/lib/data/portal";
import { brl, dateBR } from "@/lib/format";
export const Route = createFileRoute("/_authenticated/portal/empreendimentos/")({ head: () => ({ meta: [
 { title: "Meus empreendimentos — Portal MD70" }, { name: "description", content: "Acompanhe os empreendimentos dos quais você participa." },
 { property: "og:title", content: "Meus empreendimentos — Portal MD70" }, { property: "og:description", content: "Evolução privada dos seus projetos." },
] }), component: Projects });
function Projects(){return <><PortalHeading eyebrow="Projetos" title="Meus empreendimentos"><p>Acompanhe obra, orçamento e resultados dos projetos em que você participa.</p></PortalHeading><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{getInvestorDevelopments().map((d)=>{const inv=getInvestmentByDevelopment(d.id); return <Link key={d.id} to="/portal/empreendimentos/$id" params={{id:d.id}} className="group border bg-card"><div className="overflow-hidden"><img src={d.image} alt={d.name} className="photo aspect-[4/3] w-full object-cover transition-transform duration-700 group-hover:scale-[1.03]"/></div><div className="p-6"><div className="flex justify-between gap-4"><div><p className="eyebrow">{d.city}</p><h2 className="mt-2 font-display text-3xl text-primary">{d.name}</h2></div><span className="text-xs text-muted-foreground">{d.status}</span></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs"><span>Conclusão</span><span>{d.progress}%</span></div><div className="h-1.5 bg-muted"><div className="h-full bg-primary" style={{width:`${d.progress}%`}}/></div></div><dl className="mt-6 grid grid-cols-2 gap-4 border-t pt-5 text-sm"><div><dt className="text-xs text-muted-foreground">Investimento</dt><dd className="num mt-1 font-semibold">{brl(inv?.invested ?? 0)}</dd></div><div><dt className="text-xs text-muted-foreground">Previsão</dt><dd className="mt-1 font-semibold">{dateBR(d.forecast)}</dd></div></dl></div></Link>})}</div></>}
