import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { PortalHeading } from "@/components/portal/PortalLayout";
import { getInvestments } from "@/lib/data/portal";
import { brl, dateBR, pct } from "@/lib/format";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/portal/investimentos")({ head: () => ({ meta: [
  { title: "Meus investimentos — Portal MD70" }, { name: "description", content: "Seus investimentos e movimentações na MD70." },
  { property: "og:title", content: "Meus investimentos — Portal MD70" }, { property: "og:description", content: "Visão privada da sua carteira." },
] }), component: Investments });
function Investments() { const [open, setOpen] = useState<string | null>(null); const list = getInvestments(); return <><PortalHeading eyebrow="Carteira" title="Meus investimentos"><p>Valores, rentabilidade e histórico financeiro por projeto.</p></PortalHeading><div className="space-y-4">{list.map((i) => <article key={i.id} className="border bg-card"><button onClick={() => setOpen(open === i.id ? null : i.id)} className="grid w-full gap-5 p-5 text-left sm:grid-cols-[5rem_1fr_repeat(3,minmax(7rem,auto))_2rem] sm:items-center"><img src={i.development.image} alt="" className="photo aspect-square w-20 object-cover"/><div><h2 className="font-display text-2xl text-primary">{i.development.name}</h2><p className="text-xs text-muted-foreground">Entrada em {dateBR(i.entryDate)} · {i.status}</p></div><Metric l="Investido" v={brl(i.invested)}/><Metric l="Atualizado" v={brl(i.value)}/><Metric l="Rentabilidade" v={pct(i.rent)} positive/><ChevronDown className={cn("size-4 transition-transform", open === i.id && "rotate-180")}/></button>{open === i.id && <div className="border-t p-6"><h3 className="font-semibold text-primary">Histórico financeiro</h3><div className="mt-4 grid gap-6 md:grid-cols-3">{(["Aporte","Reinvestimento","Resgate"] as const).map((type) => <div key={type}><p className="eyebrow">{type === "Aporte" ? "Aportes" : `${type}s`}</p><div className="mt-3 divide-y">{i.transactions.filter((t) => t.type === type).map((t) => <div key={t.date} className="flex justify-between py-3 text-sm"><span className="text-muted-foreground">{dateBR(t.date)}</span><span className="num font-medium">{brl(Math.abs(t.amount))}</span></div>)}{!i.transactions.some((t) => t.type === type) && <p className="py-3 text-sm text-muted-foreground">Nenhuma movimentação.</p>}</div></div>)}</div><Link to="/portal/empreendimentos/$id" params={{ id: i.development.id }} className="mt-6 inline-block text-sm font-semibold text-primary underline underline-offset-4">Ver empreendimento</Link></div>}</article>)}</div></>; }
function Metric({ l,v,positive }: {l:string;v:string;positive?:boolean}) { return <div><p className="text-xs text-muted-foreground">{l}</p><p className={cn("num mt-1 font-semibold", positive && "text-positive")}>{v}</p></div>; }
