import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { PortalHeading } from "@/components/portal/PortalLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/portal/perfil")({head:()=>({meta:[{title:"Meu perfil — Portal MD70"},{name:"description",content:"Dados cadastrais e preferências de comunicação."},{property:"og:title",content:"Meu perfil — Portal MD70"},{property:"og:description",content:"Gerencie seus dados privados."}]}),component:Perfil});
function Perfil(){const {user}=Route.useRouteContext();const [profile,setProfile]=useState({full_name:"",phone:"",address:"",city:"",pref_email:true,pref_whatsapp:true});const [saving,setSaving]=useState(false);useEffect(()=>{supabase.from("profiles").select("full_name,phone,address,city,pref_email,pref_whatsapp").eq("id",user.id).maybeSingle().then(({data})=>{if(data)setProfile({full_name:data.full_name??"",phone:data.phone??"",address:data.address??"",city:data.city??"",pref_email:data.pref_email,pref_whatsapp:data.pref_whatsapp})})},[user.id]);async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const{error}=await supabase.from("profiles").update({...profile,updated_at:new Date().toISOString()}).eq("id",user.id);setSaving(false);if(error)toast.error("Não foi possível salvar.");else toast.success("Dados atualizados.")}return <><PortalHeading eyebrow="Minha conta" title="Perfil"><p>Atualize seus dados de contato e como prefere receber informações.</p></PortalHeading><form onSubmit={save} className="max-w-3xl border bg-card p-6 md:p-9"><div className="grid gap-6 sm:grid-cols-2"><Field label="Nome completo" value={profile.full_name} onChange={v=>setProfile({...profile,full_name:v})}/><div><Label>E-mail</Label><Input value={user.email??""} disabled className="mt-2 h-11"/><p className="mt-1 text-xs text-muted-foreground">O e-mail de acesso não pode ser alterado aqui.</p></div><Field label="Telefone" value={profile.phone} onChange={v=>setProfile({...profile,phone:v})}/><Field label="Cidade" value={profile.city} onChange={v=>setProfile({...profile,city:v})}/><div className="sm:col-span-2"><Field label="Endereço" value={profile.address} onChange={v=>setProfile({...profile,address:v})}/></div></div><div className="mt-9 border-t pt-7"><h2 className="font-display text-2xl text-primary">Preferências de comunicação</h2><div className="mt-5 space-y-4"><Toggle label="Receber comunicados por e-mail" checked={profile.pref_email} set={v=>setProfile({...profile,pref_email:v})}/><Toggle label="Receber atualizações pelo WhatsApp" checked={profile.pref_whatsapp} set={v=>setProfile({...profile,pref_whatsapp:v})}/></div></div><Button type="submit" size="lg" className="mt-8" disabled={saving}>{saving?"Salvando…":"Salvar alterações"}</Button></form></>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><Label>{label}</Label><Input value={value} onChange={e=>onChange(e.target.value)} maxLength={200} className="mt-2 h-11"/></div>};function Toggle({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void}){return <label className="flex items-center justify-between gap-4 border p-4 text-sm"><span>{label}</span><Switch checked={checked} onCheckedChange={set}/></label>}
